[colors.bright]
black = "#11242f"
blue = "#589de2"
cyan = "#5db5c8"
green = "#5ea965"
magenta = "#92b3df"
red = "#e56567"
white = "#e7e7f1"
yellow = "#e5be4e"

[colors.cursor]
cursor = "#e7e7f1"
text = "#11242f"

[colors.normal]
black = "#11242f"
blue = "#4674a2"
cyan = "#357a89"
green = "#3f8f48"
magenta = "#424f9e"
red = "#954445"
white = "#9ab4c2"
yellow = "#aa8455"

[colors.primary]
background = "#11242f"
foreground = "#e7e7f1"

[font]
size = 11.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.offset]
x = -1
y = -1

[keyboard]
bindings = [
  { key = "V", mods = "Control", action = "Paste" },
  { chars = "\u001B[27;5;9~", key = "Tab", mods = "Control" },
  { chars = "\u001B[27;6;9~", key = "Tab", mods = "Control|Shift" },
  { chars = "\u001B[70;5u", key = "F", mods = "Control|Shift" },
  { chars = "\u001B[80;5u", key = "P", mods = "Control|Shift" },
  { chars = "\u001B[82;5u", key = "R", mods = "Control|Shift" },
]

[window]
decorations = "full"
opacity = 0.9

[window.padding]
x = 18
y = 18
