#!/bin/zsh

# export DOCKER_HOST=tcp://0.0.0.0:2375

# export ZSH_NO_COMPILE=1

# [ -n $DISPLAY ] && export DISPLAY=localhost:0


# yarn
# export PATH="$PATH:${HOME}/.yarn/bin"

# vimwiki
# read -r -d '' VIMWIKI_LIST <<EOF
# [ \
# 	\{'path': '~/.local/wiki', 'syntax': 'markdown', 'ext': '.md'\}, \
# ]
# EOF
# export VIMWIKI_LIST
