#!/bin/bash

export OS_RELEASE=$(awk -F= '/^NAME/{print $2}' /etc/os-release | sed 's/"//g')
export KERNEL_TYPE=$(uname -r)

INSTALL_NAME='undefined'


this_is_called(){
  [ -n $1 ] && INSTALL_NAME="$1"
}

command_exists(){
  command -v $INSTALL_NAME > /dev/null; return $? 
}

install_or_skip(){
  if [ $1 -eq 0 ]; then
    echo "[INSTALL] $INSTALL_NAME"
    return 0
  else
    echo "[SKIP]    $INSTALL_NAME"
    exit
  fi
}

unsupported_platform(){
  if [ $1 -ne 0 ]; then
    return 0
  else
    echo "[UNSUP]   $INSTALL_NAME"
    exit
  fi
}

# # deprecated
# condition_exists(){
#   if [ $2 -eq 0 ]; then
#     echo "[SKIP]    $1"
#     return 0
#   else
#     echo "[INSTALL] $1"
#     return 1
#   fi
# }

# _print_install(){
#   echo "[INSTALL] $1"
# }

# _print_skip(){
#   echo "[INSTALL] $1"
# }
