#!/bin/zsh

export OS_RELEASE=$(awk -F= '/^NAME/{print $2}' /etc/os-release | sed 's/"//g')
export KERNEL_TYPE=$(uname -r)

INSTALL_NAME='undefined'


this_is_called(){
  [ -n $1 ] && INSTALL_NAME="$1"
}

we_are_on(){
  case "$OS_RELEASE" in
    'Arch Linux')       [[ "$1" == 'Arch'   ]] ;;
    'Debian GNU/Linux') [[ "$1" == 'Debian' ]] ;;
    *)                  (return 1)             ;;
  esac

  return $?
}

kernel_is(){
  case "$KERNEL_TYPE" in
    *Microsoft) [[ "$1" == 'Microsoft'   ]] ;;
    *)          (return 1)                  ;;
  esac

  return $?
}

command_exists(){
  if [ $# -eq 1 ]; then
    command -v "$1" > /dev/null; return $?
  else
    command -v "$INSTALL_NAME" > /dev/null; return $?
  fi
}

install_or_skip(){
  if [ $1 -eq 0 ]; then
    echo "[INSTALL] $INSTALL_NAME"
    return 0
  else
    echo "[SKIP]    $INSTALL_NAME"
    exit
  fi
}

unsupported_platform(){
  if [ $# -eq 1 ] && [ $1 -ne 0 ]; then
    return 0
  else
    echo "[UNSUP]   $INSTALL_NAME"
    exit
  fi
}
