#!/bin/bash

source ${DOTFILES}/scripts/install/_functions

this_is_called 'fzf'


[ ! -e ~/bin/fzf ]
install_or_skip $?


git clone --depth 1 https://github.com/junegunn/fzf.git ~/.local/share/fzf
~/.local/share/fzf/install --bin
ln -s ~/.local/share/fzf/bin/fzf ~/bin/fzf
chmod +x ~/bin/fzf
