#!/bin/bash
source ${DOTFILES}/scripts/install/_functions

this_is_called 'hub'


[ ! -f ~/bin/hub ]
install_or_skip $?


HUB_VERSION="hub-linux-amd64-2.3.0-pre10"
HUB_URL="https://github.com/github/hub/releases/download/v2.3.0-pre10/${HUB_VERSION}.tgz"

wget "$HUB_URL" -q --show-progress -P /tmp
tar xf "/tmp/${HUB_VERSION}.tgz" -C /tmp

mkdir -p ~/bin
mkdir -p ~/.local/share/completion
mv "/tmp/${HUB_VERSION}/bin/hub" ~/bin
mv "/tmp/${HUB_VERSION}/etc/hub.zsh_completion" ~/.local/share/completion/_hub
chmod +x ~/.local/share/completion/_hub

rm -r /tmp/${HUB_VERSION}{,.tgz}
