#!/bin/bash
source _functions

NAME='hub'


[ -f ~/bin/hub ]
condition_exists $NAME $?
[ $? -eq 0 ] && return 0


HUB_VERSION="hub-linux-amd64-2.3.0-pre10"
HUB_URL="https://github.com/github/hub/releases/download/v2.3.0-pre10/${HUB_VERSION}.tgz"

wget "$HUB_URL" -q --show-progress -P /tmp
tar xf "/tmp/${HUB_VERSION}.tgz" -C /tmp

mv "/tmp/${HUB_VERSION}/bin/hub" ~/bin
rm -r /tmp/${HUB_VERSION}{,.tgz}
