#!/bin/zsh
source ${DOTFILES}/scripts/install/_functions


this_is_called 'toast'


! command_exists 'toast'
install_or_skip $?


if kernel_is 'Microsoft'
then
  sudo cat <<- EOF > /usr/local/bin/toast
  #!/bin/sh
  powershell.exe -command "New-BurntToastNotification -Text '\$@'"
  EOF
  sudo chmod +x /usr/local/bin/toast
else
  unsupported_platform
fi
