#!/bin/bash
source ${DOTFILES}/scripts/install/_functions

this_is_called 'toast'

! command_exists
install_or_skip $?

case "$KERNEL_TYPE" in
  *Microsoft)
	sudo cat <<- EOF > /usr/local/bin/toast
	#!/bin/sh
	powershell.exe -command "New-BurntToastNotification -Text '\$@'"
	EOF
	sudo chmod +x /usr/local/bin/toast
    ;;
  *)
    unsupported_platform
esac
