#!/bin/bash
source ${DOTFILES}/scripts/install/_functions

this_is_called 'wslpath'

[[ "$KERNEL_TYPE" != *Microsoft ]]
unsupported_platform $?

[ ! -f ~/bin/wslpath ]
install_or_skip $?


wget 'https://github.com/darealshinji/scripts/raw/master/wslpath' \
  -q --show-progress -O ~/bin/wslpath
chmod +x ~/bin/wslpath


