#!/usr/bin/env bash

command_exists() {
    type "$1" > /dev/null 2>&1
}

echo "Installing dotfiles."


echo "Initializing submodule(s)"
git submodule update --init --recursive

 
mkdir -p ~/bin
mkdir -p ~/.local # local files directory
mkdir -p ~/.local/share
mkdir -p ~/.local/share/misc


source scripts/link.sh


# install fzf if not installed
if [ ! -d ~/.local/share/fzf ]; then
	echo "installing fzf"
	git clone --depth 1 https://github.com/junegunn/fzf.git ~/.local/share/fzf
	~/.local/share/fzf/install --bin
	ln -s ~/.local/share/fzf/bin/fzf ~/bin/fzf
	chmod +x ~/bin/fzf
fi

# install wslpath
if [ ! -f ~/bin/wslpath ]; then
	echo "installing wslpath"
	wget https://github.com/darealshinji/scripts/raw/master/wslpath -O ~/bin/wslpath
	chmod +x ~/bin/wslpath
fi

if  [ ! -f ~/bin/hub ]; then
	echo "installing hub"

	HUB_VERSION="hub-linux-amd64-2.3.0-pre10"
	HUB_URL="https://github.com/github/hub/releases/download/v2.3.0-pre10/${HUB_VERSION}.tgz"

	wget "$HUB_URL"
	tar xf "${HUB_VERSION}.tgz"

	mv "${HUB_VERSION}/bin/hub" ~/bin
	rm -r ${HUB_VERSION}{,.tgz}
fi

echo "Done. Reload your terminal."
