#!/usr/bin/env bash

export DOTFILES=$(pwd)

echo "Installing dotfiles."

echo "Initializing submodule(s)"
git submodule update --init --recursive

 
mkdir -p ~/bin
mkdir -p ~/.local # local files directory
mkdir -p ~/.local/share
mkdir -p ~/.local/share/misc

# cd scripts
source scripts/install.sh

source scripts/link.sh

echo "Done. Reload your terminal."
