#!/bin/bash

export DOTFILES=$(pwd)

# initialize core module
source $DOTFILES/scripts/core


echo "Installing dotfiles."


echo "Initializing submodule(s)"
git submodule update --init --recursive


mkdir -p ~/bin
mkdir -p ~/.local # local files directory
mkdir -p ~/.local/share
mkdir -p ~/.local/share/dotfiles
mkdir -p ~/.local/share/misc

# take care of all local files
source scripts/setup/folder-structure

# cd scripts
source scripts/setup/link

echo "Done. Reload your terminal."
