# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [
    "dm-snapshot"
    "uinput"
    "amdgpu"
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "zfs" ];
  boot.zfs.package = pkgs.zfs_unstable;

  boot.kernelParams = [
    "quiet"
    "video=HDMI-A-1:3840x2160@60"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXROOT";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/49C7-2B5F";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/a5286d98-6422-4a57-adce-ccb0caefe6b6";
    fsType = "btrfs";
    options = [
      "rw"
      "relatime"
      "space_cache=v2"
      "subvol=/@root"
    ];
  };

  fileSystems."/mnt/ssd2" = {
    device = "/dev/disk/by-uuid/9c24ebbb-ad5f-4a05-98c9-489ce5a6dfed";
    fsType = "btrfs";
    options = [
      "rw"
      "relatime"
      "ssd"
      "space_cache=v2"
      "subvol=/@root"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
