#!/bin/zsh

# OS release info
# for example: Arch Linux
[ -e /etc/os-release ] \
  && export OS_RELEASE=$(awk -F= '/^NAME/{print $2}' /etc/os-release | sed 's/"//g') \
  || export OS_RELEASE='Unknown'

# kernel info
# for example: 4.19.67-microsoft-standard
export KERNEL_TYPE=$(uname -r)
