#!/bin/zsh


echo "setting up folder structure"


cat << EOF
relevant folders:
|--- ${HOME}/
| |--- bin/             local script files
|
|--- .local/            local files
  |---> share/          temporary files
  |---> config/         local configuration files
    |---> backup/        backup config
    |---> zsh/           zsh config
EOF


mkdir -p "$HOME/bin"

mkdir -p "$HOME/.local"
mkdir -p "$HOME/.local/backup"
mkdir -p "$HOME/.local/config"
mkdir -p "$HOME/.local/config/backup"
mkdir -p "$HOME/.local/config/backup/`hostname`"
mkdir -p "$HOME/.local/config/zsh"
mkdir -p "$HOME/.local/share"


cp -rn $DOTFILES/template/local/* $HOME/.local


echo "file structure setup complete"
