#!/bin/zsh


INSTALL_NAME='undefined'


this_is_called(){
  [ -n $1 ] && INSTALL_NAME="$1"
}

we_are_on(){
  case "$OS_RELEASE" in
    'Arch Linux')       [[ "$1" == 'Arch'   ]] ;;
    'Debian GNU/Linux') [[ "$1" == 'Debian' ]] ;;
    *)                  (return 1)             ;;
  esac

  return $?
}

kernel_is(){
  case "$KERNEL_TYPE" in
    *microsoft*) [[ "$1" == 'windows'     ]] ;;
    *)           (return 1)                  ;;
  esac

  return $?
}

install_if_true(){
  if [ $1 -eq 0 ]; then
    echo "[INSTALL]        $INSTALL_NAME"
    exit
  fi
}

skip_if_true(){
  if [ $1 -eq 0 ]; then
    echo "[SKIP]           $INSTALL_NAME"
    exit
  fi
}

unsupported_platform(){
  if [ $# -eq 1 ] && [ $1 -ne 0 ]; then
    return 0
  else
    echo "[UNSUP-PLATFORM] $INSTALL_NAME"
    exit
  fi
}
