include catppuccin.conf

confirm_os_window_close 0

font_family Hack Nerd Font Mono Regular
bold_font Hack Nerd Font Mono Bold
italic_font Hack Nerd Font Mono Italic
bold_italic_font Hack Nerd Font Mono Bold Italic
font_size 11.0

window_padding_width 10
background_opacity 0.9

#modify_font cell_height 115%
modify_font cell_width 90%
