#!/bin/zsh

export dotimport(){ source "$DOTFILES/scripts/$1" }

dotimport 'core/system-info'
dotimport 'core/core-commands'



# global dotfiles initialization
# can be used in verious scripts to access dotfiles functionality
alias DOTINIT="$DOTFILES/scripts/dotinit"
