workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 6, monitor:eDP-1, gapsin:0, gapsout:0, border:0
workspace = 7, monitor:eDP-1
workspace = 8, monitor:eDP-1
workspace = 9, monitor:eDP-1
workspace = 10, monitor:eDP-1


# monitor=eDP-1,addreserved,-4,0,0,0
# monitor=eDP-1,3840x2160,1080x445,1.6
# monitor=eDP-1,disabled
# monitor=DP-1,3840x2160,1080x1872,1.5
# monitor=desc:I-O Data Device Inc LDGCWF291SD 13SM000810CM,2560x1080@74.99100,0x0,1,transform,1

exec-once = xrandr --output HDMI-A-1 --primary
