#!/bin/zsh

output="$(deadbeef --nowplaying-tf "%ispaused% %title%" 2>/dev/null)"

# if playing
if [ "${output:0:1}" -ne 1 ]; then
  echo "${output:1}"
else
  echo
fi

# if [ -f /tmp/foobar-now-playing.txt ]; then
#   state="$(cat /tmp/foobar-now-playing.txt | head -n1)"

#   if [[ "$state" =~ "playing: " ]]; then
#     echo "${state##*"playing: "}"
#   else
#     echo ""
#   fi
# fi
