#!/bin/zsh

# sync package list first
yay -Sy > /dev/null 2>&1


# get list and count of updates
if ! updates=$(yay -Qu 2>/dev/null | wc -l); then
    updates=0
fi

# print the available updates if more than 0
if [ "$updates" -gt 0 ]; then
    echo " $updates"
else
    echo ""
fi
